---
title: "[XSTSF] Data processing"
author: Yibing Shi
date: "Last updated: 2023-07-28"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(readxl)
library(dplyr)
library(tidyverse)
```


## F0
### Import raw data and labels 
```{r import-data-f0, message=FALSE, warning=FALSE}
# f0 data for mono-/di-/tri-syllables under citation (ct) or focus conditions
f0_mono_pre <- read_excel('raw_data/mono_f0_all_2.xlsx')
f0_di_ct_pre <- read_excel('raw_data/f0_ct.xlsx', sheet = 'di')
f0_tri_ct_pre <- read_excel('raw_data/f0_ct.xlsx', sheet = 'tri')
f0_focus_pre <- read_excel('raw_data/f0_focus.xlsx')

# data labels 
label_mono <- read_excel('raw_data/labels.xlsx', sheet = 'mono')
label_di_ct <- read_excel('raw_data/labels.xlsx', sheet = 'citation.di')
label_tri_ct <- read_excel('raw_data/labels.xlsx', sheet = 'citation.tri')
label_focus <- read_excel('raw_data/labels.xlsx', sheet = 'focus')
```

## Data cleaning  
```{r data-cleaning, message=FALSE, warning=FALSE}
## Labels 
# monosyllables
label_mono <- label_mono %>%
  pivot_longer(
    cols = S1:S8,
    names_to = 'speaker',
    values_to = 'tone'
  ) %>%
  mutate(mono_no = as.numeric(mono_no),
         tone = ifelse(tone == 'HM', 'HL',
                       ifelse(tone == 'LM', 'LH', tone))) 

# disyllables
label_di_ct <- label_di_ct %>%
  left_join(label_mono[, -1], by = c('mono_no_1' = 'mono_no')) %>%
  rename(mono_tone_1 = tone) %>%
  left_join(label_mono[, -1], by = c('mono_no_2' = 'mono_no', 'speaker')) %>%
  rename(mono_tone_2 = tone) %>%
  mutate(citation_tone = paste(mono_tone_1, mono_tone_2, sep = '')) 

# trisyllables
label_tri_ct <-label_tri_ct %>%
  pivot_wider(names_from = syllable_no, values_from = mono_no) %>%
  rename(mono_no_1 = '1', mono_no_2 = '2', mono_no_3 = '3') %>%
  left_join(label_mono[, -1], by = c('mono_no_1' = 'mono_no')) %>%
  rename(mono_tone_1 = tone) %>%
  left_join(label_mono[, -1], by = c('mono_no_2' = 'mono_no', 'speaker')) %>%
  rename(mono_tone_2 = tone) %>%
  left_join(label_mono[, -1], by = c('mono_no_3' = 'mono_no', 'speaker')) %>%
  rename(mono_tone_3 = tone) %>%
  mutate(citation_tone = paste(mono_tone_1, mono_tone_2, mono_tone_3, sep = ''),) %>% 
  select(-syntax) %>%
  rename(syntax = syntax_first_tone)


## f0 data
# monosyllables
# 8 speakers * 54 tokens * 10 normalised time points = 4320
f0_mono_pre <- f0_mono_pre %>%
  left_join(distinct(label_mono[, c(1, 2)]), by = 'mono_no') %>%
  rename(token_no = mono_no,
         citation_tone = tone) %>%
  mutate(syllable_no = NA,
         sandhi_tone = NA,
         syntax = NA,
         focus_no = NA,
         diortri = NA,
         focus_condition = 'citation') %>%
  rename(citation_no = token_no)

# disyllables citation
# 8 speakers * 52 tokens * 10 normalised time points * 2 syllables = 8320  
f0_di_ct_pre <- f0_di_ct_pre %>%
  rename(token_no = di_no,
         sandhi_tone = sandhi) %>%
  select(-citation) %>%
  left_join(label_di_ct[, c(1, 3, 6, 9)], by = c('token_no', 'speaker')) %>%
  mutate(focus_no = NA,
         diortri = 'di',
         focus_condition = 'citation') %>%
  rename(citation_no = token_no)

# trisyllables citation
# 8 speakers * 44 tokens * 10 normalised time points * 3 syllables = 10560 
f0_tri_ct_pre <- f0_tri_ct_pre %>%
  rename(token_no = tri.no,
         syllable_no = syllable.no,
         sandhi_tone = sandhi) %>%
  select(-citation) %>%
  left_join(label_tri_ct[, c(1:3, 7, 11)], by = c('token_no', 'speaker')) %>%
  mutate(time = rep(1:30, times = 10560/30),
         focus_no = NA,
         diortri = 'tri',
         focus_condition = 'citation') %>%
  rename(citation_no = token_no)

# focus
# 8 speakers * (115 disyllables * 2 + 219 trisyllables * 3) * 10 normalised time points = 70960
# see 'raw_data/labels.xlsx/check' for details
f0_focus_pre <- f0_focus_pre %>%
  left_join(label_focus, by = 'focus_no')

f0_di_focus_pre <- f0_focus_pre %>% filter(diortri == 'di')
f0_tri_focus_pre <- f0_focus_pre %>% filter(diortri == 'tri')

f0_di_focus_pre <- f0_di_focus_pre %>%
  mutate(time = rep(1:20, times = 18400/20)) %>%
  left_join(label_di_ct[, c(2:3, 6, 9)], by = c('citation_no' = 'token_no', 'speaker')) %>%
  mutate(sandhi_tone = NA)

f0_tri_focus_pre <- f0_tri_focus_pre %>%
  mutate(time = rep(1:30, times = 52560/30)) %>%
  left_join(label_tri_ct[, c(2:3, 7, 11)], by = c('citation_no' = 'token_no', 'speaker')) %>%
  mutate(sandhi_tone = NA)


## Data normalisation
f0_all_pre <- rbind(f0_mono_pre, f0_di_ct_pre, f0_tri_ct_pre, f0_di_focus_pre, f0_tri_focus_pre)

f0_all_pre <- f0_all_pre %>%
  group_by(speaker) %>%
  mutate(norm_f0 = scale(log(f0))) %>%
  ungroup() %>%
  mutate(ind_no = ifelse(focus_condition == 'citation', paste(speaker, citation_no, sep = '_'),
                         paste(speaker, citation_no, focus_condition, sep = '_')))
```


## Saving
```{r saving}
save.image('XSTSF_production.RData')
```

