---
title: "Construct data for average citation tone f0 values in di- and tri-syllabic contexts"
output: html_document
date: "2024-04-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(plyr)
library(tidyr)
library(tidyverse)
library(rlang)
```

## Construct citation tone combination data
```{r}
std <- function(x) sd(x)/sqrt(length(x))

detach(package:plyr)
f0_mono_ct_avg <- f0_all_pre %>% filter(is.na(diortri) == TRUE) %>% 
  mutate(citation_tone = case_when(
    str_sub(citation_tone, end = 2) == 'HH' ~ 'HH',
    str_sub(citation_tone, end = 2) == 'HL' ~ 'HL',
    .default = citation_tone
  )) %>% 
  filter(!(citation_tone == 'HL' & speaker == 'S6')) %>% 
  group_by(citation_tone, time) %>% 
  summarise(meanf0 = mean(norm_f0),
              se = std(norm_f0)) %>% 
  ungroup() %>% 
  dplyr::rename(tone = citation_tone)

f0_di_ct_avg <- cross_join(f0_mono_ct_avg, f0_mono_ct_avg, suffix = c("_1", "_2")) %>% 
  mutate(citation_tone = paste(tone_1, tone_2, sep = '_')) %>% 
  pivot_longer(-citation_tone,
               cols_vary = "slowest",
               names_to = c(".value", "syllable"),
               names_pattern = "(.+)_(.+)") %>% 
  distinct() %>% 
  mutate(time = as.numeric(time)) %>% 
  mutate(time = ifelse(syllable == '2', time+10, time))

di_int <- cross_join(f0_mono_ct_avg, f0_mono_ct_avg, suffix = c("_1", "_2")) %>% distinct()
mono_int <- f0_mono_ct_avg
colnames(mono_int) <- paste0(colnames(mono_int), '_3')

f0_tri_ct_avg <- 
  cross_join(di_int, mono_int)%>% 
  mutate(citation_tone = paste(tone_1, tone_2, tone_3, sep = '_')) %>% 
  pivot_longer(-citation_tone,
               cols_vary = "slowest",
               names_to = c(".value", "syllable"),
               names_pattern = "(.+)_(.+)") %>% 
  distinct() %>% 
  mutate(time = as.numeric(time))
```