---
title: "Analysis of disyllabic Verb-Object phrases citation tone sandhi patterns in
  Xiangshan"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(gridExtra) 
library(ggthemes)
library(viridis)
library(plotly)
library(ggrepel)
library(kml)
```

# Data preparations  
```{r data-construction, cache=FALSE}
load("XSTSF_production.RData")
source('functions.R')
```


```{r data-construction, cache=FALSE}
f0_all_ct <- f0_all_pre %>% filter(focus_condition == 'ct' ) %>% 
  group_by(speaker) %>% 
  mutate(norm_f0 = scale(log(f0))) %>% 
  ungroup()

f0_di_ct_vo <- f0_all_ct %>% 
  filter(syntax %in% c('V') & diortri == 'di' & is.na(sandhi_tone) == FALSE & ind_no != 'S5_22_ct') 
  
f0_di_ct_vo_h <- f0_di_ct_vo %>% 
  filter( grepl('^H', sync_tone1)) %>% 
  mutate(sandhi_tone = ifelse(sandhi_tone %in% c('MMMH', 'HHHH'), 'MMHH', 
                              ifelse(sandhi_tone == 'MHHL', 'MMHL', sandhi_tone))) %>% 
  mutate(sync_tone1 = ifelse(sync_tone1 == 'RF', 'LHL', sync_tone1),
         sync_tone2 = ifelse(sync_tone2 == 'RF', 'LHL', sync_tone2)) %>% 
  mutate(sync_tone1 = factor(sync_tone1, levels = c('HH', 'HL', 'LH', 'LHL')),
         sync_tone2 = factor(sync_tone2, levels = c('HH', 'HL', 'LH', 'LHL'))) %>% 
  mutate(hist_tone1 = factor(hist_tone1, levels = c('yinping', 'yinshang')),
         hist_tone2 = factor(hist_tone2, levels = c('yinping', 'yinshang', 'yinqu', 'yangping', 'yangqu'))) %>%
  mutate(sandhi_tone = factor(sandhi_tone, levels = c('HMML', 'MMHL', 'MMHH')))
  
f0_di_ct_vo_hp <- f0_di_ct_vo_h %>% filter(hist_tone1 == 'yinping')
f0_di_ct_vo_hs <- f0_di_ct_vo_h %>% filter(hist_tone1 == 'yinshang')

f0_di_ct_vo_l <- f0_di_ct_vo %>% filter( grepl('^[LR]', sync_tone1)) %>% 
  mutate(sync_tone1 = ifelse(sync_tone1 == 'RF', 'LHL', sync_tone1),
         sync_tone2 = ifelse(sync_tone2 == 'RF', 'LHL', sync_tone2)) %>% 
  mutate(sync_tone1 = factor(sync_tone1, levels = c('HH', 'HL', 'LH', 'LHL')),
         sync_tone2 = factor(sync_tone2, levels = c('HH', 'HL', 'LH', 'LHL'))) %>% 
  mutate(hist_tone2 = factor(hist_tone2, levels = c('yinping', 'yinqu', 'yangping', 'yangqu'))) %>%
  mutate(sandhi_tone = factor(sandhi_tone, levels = c('LLHH', 'LLHL', 'LLLH', 'LLRF')))
f0_di_ct_vo_ls <- f0_di_ct_vo_l %>% filter(hist_tone1 == 'yangshang')

unique(f0_di_ct_vo_h$sandhi_tone)
```

# Initial data inspection

```{r fig.height=8}
# yinping-initial VO
ggplotly(draw_by(f0_di_ct_vo_hp, 'speaker'), tooltip = c('text', 'x'))

# yinshang-initial VO
ggplotly(draw_by(f0_di_ct_vo_hs, 'speaker'), tooltip = c('text', 'x'))

# yangshang-initial VO
ggplotly(draw_by(f0_di_ct_vo_ls, 'speaker'), tooltip = c('text', 'x'))
```


# Auditory categorisation

```{r, warning=FALSE, message=FALSE}
# H-register-initial
p_cluster(f0_di_ct_vo_h, sandhi_tone)
ggsave(filename = file.path(plot_dir, "vo_h_human.jpeg"),width = 8, height = 4)

p_sub_cluster(f0_di_ct_vo_h, sync_tone2, sandhi_tone)
p_sub_cluster(f0_di_ct_mh_h, sync_tone2, sandhi_tone)+ggtitle('Adjective-Noun phrases')

p_sub_cluster(filter(f0_di_ct_vo_h, sandhi_tone == 'HMML'), sync_tone2, sandhi_tone)+
  labs(fill = 'second synchronic tone', color = 'second synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_h_incom2.jpeg"),width = 6, height = 3)
p_sub_cluster(filter(f0_di_ct_vo_h, sandhi_tone == 'MMHL' & sync_tone2 != 'HH'), sync_tone2, sandhi_tone)+
  labs(fill = 'second synchronic tone', color = 'second synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_h_incom1.jpeg"),width = 6, height = 3)

# L-register-initial
p_cluster(f0_di_ct_vo_ls, sandhi_tone)
ggsave(filename = file.path(plot_dir, "vo_l_human.jpeg"),width = 8, height = 4)

p_sub_cluster(f0_di_ct_vo_ls, sync_tone2, sandhi_tone)
```

# Distribution analysis

H-register-initial
```{r}
# mono tone
distri_prop2(f0_di_ct_vo_h, hist_tone1, sync_tone1)+
  xlab('initial syllable historical tone')+labs(fill = 'synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_h_tone1.jpeg"),width = 7, height = 3.5, dpi = 300)
distri_prop2(f0_di_ct_vo_h, hist_tone2, sync_tone2)+
  xlab('second syllable historical tone')+labs(fill = 'synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_h_tone2.jpeg"),width = 7, height = 3.5, dpi = 300)

# by initial tone
distri_prop2(f0_di_ct_vo_h, hist_tone1, sandhi_tone)+xlab('initial historical tone')
ggsave(filename = file.path(plot_dir, "vo_h_dist_tone1_hist.jpeg"),width = 7, height = 3.5, dpi = 300)
distri_prop2(f0_di_ct_vo_h, sync_tone1, sandhi_tone)+xlab('initial synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_h_dist_tone1_sync.jpeg"),width = 7, height = 3.5, dpi = 300)
distri_prop(f0_di_ct_vo_h, sync_tone1, sandhi_tone, hist_tone1)

# by second tone
distri_prop2(f0_di_ct_vo_h, hist_tone2, sandhi_tone)+xlab('second historical tone')
ggsave(filename = file.path(plot_dir, "vo_h_dist_tone2_hist.jpeg"),width = 7, height = 3.5, dpi = 300)
distri_prop2(f0_di_ct_vo_h, sync_tone2, sandhi_tone)+xlab('second synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_h_dist_tone2_sync.jpeg"),width = 7, height = 3.5, dpi = 300)
#distri_prop(f0_di_ct_vo_h, hist_tone2, sandhi_tone, sync_tone2)

# by speaker
distri_prop2(f0_di_ct_vo_h, speaker, sandhi_tone)+xlab('speaker')
ggsave(filename = file.path(plot_dir, "vo_h_dist_speaker.jpeg"),width = 8, height = 4, dpi = 300)
distri_prop(f0_di_ct_vo_h, speaker, sandhi_tone, sync_tone2)
distri_prop(f0_di_ct_vo_h, speaker, sandhi_tone, hist_tone2)

distri_prop(f0_di_ct_vo_hp, speaker, sandhi_tone, sync_tone2)
distri_prop(f0_di_ct_vo_hs, speaker, sandhi_tone, sync_tone2)

# by item
distri_prop2(f0_di_ct_vo_h, speaker, sandhi_tone)
```



L-register-initial
```{r}
# mono tone
distri_prop2(f0_di_ct_vo_ls, hist_tone1, sync_tone1)+
  xlab('initial syllable historical tone')+labs(fill = 'synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_l_tone1.jpeg"),width = 7, height = 3.5, dpi = 300)
distri_prop2(f0_di_ct_vo_ls, hist_tone2, sync_tone2)+
  xlab('second syllable historical tone')+labs(fill = 'synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_l_tone2.jpeg"),width = 7, height = 3.5, dpi = 300)

# by initial tone
distri_prop2(f0_di_ct_vo_ls, hist_tone1, sandhi_tone)
distri_prop2(f0_di_ct_vo_ls, sync_tone1, sandhi_tone)+xlab('initial synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_l_dist_tone1.jpeg"),width = 7, height = 3.5, dpi = 300)

# by second tone
distri_prop2(f0_di_ct_vo_ls, hist_tone2, sandhi_tone)
distri_prop2(f0_di_ct_vo_ls, sync_tone2, sandhi_tone)+xlab('second synchronic tone')
ggsave(filename = file.path(plot_dir, "vo_l_dist_tone2.jpeg"),width = 7, height = 4, dpi = 300)

# by speaker
distri_prop2(f0_di_ct_vo_ls, speaker, sandhi_tone)
ggsave(filename = file.path(plot_dir, "vo_l_dist_speaker.jpeg"),width = 8, height = 4, dpi = 300)
```


# k-means clustering 

H-register-initial
```{r}
# data preparation
f0_di_ct_vo_h_kmeans <- f0_di_ct_vo_h %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(time, norm_f0)

# k-means clustering
cluster_model <- k_means_clustering(f0_di_ct_vo_h_kmeans)
kml(cluster_model, nbClusters = 2:10) 
kml::plot(cluster_model, 3, parTraj=parTRAJ(col="clusters"))
plotAllCriterion(cluster_model)

# get cluster results
f0_di_ct_vo_h_kmeans <- f0_di_ct_vo_h_kmeans %>% 
  mutate(cluster2 = getClusters(cluster_model, 2),
         cluster3 = getClusters(cluster_model, 3))

f0_di_ct_vo_h_kmeans <- wide_to_long(f0_di_ct_vo_h_kmeans) %>% 
  mutate(syllable_no = ifelse(time < 11, '1', '2')) %>% 
  mutate(cluster2_reorder = case_when(cluster2 == 'A' ~ 'B',
                                      cluster2 == 'B' ~ 'A'),
         cluster3_reorder = case_when(cluster3 == 'C' ~ 'A',
                                      cluster3 == 'A' ~ 'B',
                                      cluster3 == 'B' ~ 'C'))

# visualisation
p_kmeans3 <- p_cluster(f0_di_ct_vo_h_kmeans, cluster3_reorder); p_kmeans3
p_kmeans2 <- p_cluster(f0_di_ct_vo_h_kmeans, cluster2_reorder); p_kmeans2

# heatmap
heatmap_df <- heatmap_data(f0_di_ct_vo_h_kmeans, cluster2_reorder) 
p_htmap2 <- compare_cluster(heatmap_df, 'cluster2_reorder'); p_htmap2

heatmap_df <- heatmap_data(f0_di_ct_vo_h_kmeans, cluster3_reorder) 
p_htmap3 <- compare_cluster(heatmap_df, 'cluster3_reorder'); p_htmap3

# combination of plots
ggarrange(p_kmeans2, p_htmap2, widths = c(1.4, 1))
ggsave(filename = file.path(plot_dir, "vo_h_kmeans2.jpeg"),width = 12, height = 4, dpi = 300)

ggarrange(p_kmeans3, p_htmap3, widths = c(1.4, 1))
ggsave(filename = file.path(plot_dir, "vo_h_kmeans3.jpeg"),width = 12, height = 4, dpi = 300)
```

mismatches
```{r}
f0_di_ct_vo_h_kmeans <- f0_di_ct_vo_h_kmeans %>% 
  mutate(sub_cluster = paste0(sandhi_tone, '_', cluster3_reorder))

cluster_hhhh <- f0_di_ct_vo_h_kmeans %>% filter(sandhi_tone == 'HHHH')
p_cluster(cluster_hhhh, sub_cluster)

cluster_mmhl <- f0_di_ct_vo_h_kmeans %>% filter(sandhi_tone == 'MMHL')
p_cluster(cluster_mmhl, sub_cluster)
ggsave(filename = file.path(plot_dir, "vo_h_mismatch.jpeg"),width = 8, height = 4)

cluster_hhhh %>% filter(sub_cluster == 'HHHH_A')
```

L-register-initial
```{r}
# data preparation
f0_di_ct_vo_ls_kmeans <- f0_di_ct_vo_ls %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(time, norm_f0)

# k-means clustering
cluster_model <- k_means_clustering(f0_di_ct_vo_ls_kmeans)
kml(cluster_model, nbClusters = 2:10) 
kml::plot(cluster_model, 4, parTraj=parTRAJ(col="clusters"))
plotAllCriterion(cluster_model)

# get cluster results
f0_di_ct_vo_ls_kmeans <- f0_di_ct_vo_ls_kmeans %>% 
  mutate(cluster4 = getClusters(cluster_model, 4),
         cluster3 = getClusters(cluster_model, 3))

f0_di_ct_vo_ls_kmeans <- wide_to_long(f0_di_ct_vo_ls_kmeans) %>% 
  mutate(syllable_no = ifelse(time < 11, '1', '2'))%>% 
  mutate(cluster4_reorder = case_when(cluster4 == 'A' ~ 'B',
                                      cluster4 == 'B' ~ 'A'),
         cluster3_reorder = case_when(cluster3 == 'C' ~ 'A',
                                      cluster3 == 'A' ~ 'B',
                                      cluster3 == 'B' ~ 'C'))

# visualisation
p_kmeans3 <- p_cluster(f0_di_ct_vo_ls_kmeans, cluster3);p_kmeans3
p_kmeans4 <- p_cluster(f0_di_ct_vo_ls_kmeans, cluster4);p_kmeans4

# heatmap
heatmap_df <- heatmap_data(f0_di_ct_vo_ls_kmeans, cluster3) 
p_htmap3 <- compare_cluster(heatmap_df, 'cluster3'); p_htmap3

heatmap_df <- heatmap_data(f0_di_ct_vo_ls_kmeans, cluster4) 
p_htmap4 <- compare_cluster(heatmap_df, 'cluster4'); p_htmap4

# combination of plots
ggarrange(p_kmeans3, p_htmap3, widths = c(1.4, 1))
ggsave(filename = file.path(plot_dir, "vo_L_kmeans3.jpeg"),width = 12, height = 4, dpi = 300)

ggarrange(p_kmeans4, p_htmap4, widths = c(1.4, 1))
ggsave(filename = file.path(plot_dir, "vo_L_kmeans4.jpeg"),width = 12, height = 4, dpi = 300)
```
mismatches
```{r}
f0_di_ct_vo_ls_kmeans <- f0_di_ct_vo_ls_kmeans %>% 
  mutate(sub_cluster = paste0(sandhi_tone, '_', cluster4))

cluster_llrf <- f0_di_ct_vo_ls_kmeans %>% filter(sandhi_tone == 'LLRF')
p_cluster(cluster_llrf, sub_cluster)

cluster_lllh <- f0_di_ct_vo_ls_kmeans %>% filter(sandhi_tone == 'LLLH')
p_cluster(cluster_lllh, sub_cluster)

cluster_llhl <- f0_di_ct_vo_ls_kmeans %>% filter(sandhi_tone == 'LLHL')
p_cluster(cluster_llhl, sub_cluster)
```

