---
title: "Analysis of disyllabic citation tone sandhi patterns in Xiangshan"
author: Yibing Shi
date: "Last updated: 2024-04-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(ggpubr)
library(viridis)
library(cowplot)
library(plotly)
library(gridExtra) 
library(ggpubr)
library(ggthemes)
library(writexl)
library(readxl)
library(kml)
```

# Data preparations  
**Construct data frame ** 
```{r data-construction, cache=FALSE}
load("XSTSF_production.RData")
source('functions.R')

# add human perceptual sandhi categories
label_sandhi <- read.csv('raw_data/sandhi_label.csv', 
                         na.strings = '') 
f0_all_pre_label <- f0_all_pre %>% 
  select(!sandhi_tone) %>% 
  left_join(label_sandhi[, c('ind_no', 'sandhi_tone', 'sandhi_tone_var', 'diortri')], 
            by = c('diortri', 'ind_no')) %>% 
  mutate(sandhi_tone_var = case_when(is.na(sandhi_tone_var) == TRUE ~ sandhi_tone,
                                     .default = sandhi_tone_var)) %>% 
  rename(normtime = time)

# get disyllabic citation data 
f0_di <- f0_all_pre_label %>% filter(diortri == 'di') 
f0_di_ct <- f0_di %>% filter(focus_condition == 'ct') %>% 
  # re-normalisation
  group_by(speaker) %>%
    mutate(f0ref = mean(f0, na.rm = T),
           norm_f0 = scale(log(f0))) %>% 
    ungroup()

# get individual datasets
f0_di_ct_lcmh <- f0_di_ct %>% filter(grepl("^[LM]", syntax_iniTone)) %>% 
  mutate(sandhi_tone = case_when(sandhi_tone == 'HLLM' ~ 'HMML',
                                 sandhi_tone == 'LLHL' ~ 'LLRF', 
                                 .default = sandhi_tone))
# check manual labels
unique(f0_di_ct_lcmh$sandhi_tone)

f0_di_ct_lcmh_h <- f0_di_ct_lcmh %>% filter( grepl('^H', mono_tone_1))
f0_di_ct_lcmh_hp <- f0_di_ct_lcmh_h %>% filter(grepl('p$', syntax_iniTone))
f0_di_ct_lcmh_hs <- f0_di_ct_lcmh_h %>% filter(grepl('s$', syntax_iniTone))
f0_di_ct_lcmh_l <- f0_di_ct_lcmh %>% filter( grepl('^[LR]', mono_tone_1)) 
f0_di_ct_lcmh_lp <- f0_di_ct_lcmh_l %>% filter(grepl('p$', syntax_iniTone))
f0_di_ct_lcmh_ls <- f0_di_ct_lcmh_l %>% filter(grepl('s$', syntax_iniTone))
```


# Initial data inspection

```{r fig.height='800px'}
# yinping-initial LC & MH
ggplotly(draw_by(f0_di_lcmh_hp, 'speaker'), tooltip = c('text', 'x'))

# yinshang-initial LC & MH
ggplotly(draw_by(f0_di_lcmh_hs, 'speaker'), tooltip = c('text', 'x'))

# yangping-initial LC & MH
ggplotly(draw_by(f0_di_lcmh_lp, 'speaker'), tooltip = c('text', 'x'))

# yangshang-initial LC & MH
ggplotly(draw_by(f0_di_lcmh_ls, 'speaker'), tooltip = c('text', 'x'))
```


# Perceptual analysis 

## H-register-initial LC & MH: average
```{r out.width='100%'}
f0_di_ct_lcmh_h <- f0_di_ct_lcmh_h %>% 
  mutate(sandhi_tone = ifelse(sandhi_tone == 'HLLM', 'HMML', sandhi_tone),
         propdur = as.integer(normtime)/20) %>% 
  unite('groupvar', ind_no, syllable_no, sep = '_', remove = FALSE) %>% 
  filter(is.na(sandhi_tone) == FALSE) %>% 
  filter(!ind_no %in% c('S2_1_ct', 'S2_11_ct', 'S2_27_ct', 'S3_5_ct', 'S3_19_ct', 'S5_27_ct')) 
  
unique(f0_di_ct_lcmh_h$sandhi_tone) # check the labels

p_cluster(f0_di_ct_lcmh_h, sandhi_tone)
```

## H-register-initial LC & MH: individual categories
```{r out.width='100%'}
p_cluster(f0_di_ct_lcmh_h, sandhi_tone, 'speaker')
```
```{r}
# examine individual cases
f0_di_ct_lcmh_h %>% filter(sandhi_tone == 'HHHH' & speaker == 'S6') %>% select('token', 'groupvar') %>% distinct()
```



# k-means clustering analysis

H-register LC & MH
```{r}
f0_di_ct_lcmh_h_kmeans <- f0_di_ct_lcmh_h %>% 
  select(-diortri, -syllable_no, -focus_no, -f0, -groupvar, -propdur) %>% 
  spread(normtime, norm_f0)

f0_di_ct_lcmh_h_cluster <- k_means(f0_di_ct_lcmh_h_kmeans)
kml(f0_di_ct_lcmh_h_cluster, nbClusters = 2:10) 
plot(f0_di_ct_lcmh_h_cluster, 4, parTraj=parTRAJ(col="clusters"))

f0_di_ct_lcmh_h_kmeans <- f0_di_ct_lcmh_h_kmeans %>% 
  mutate(cluster4 = getClusters(f0_di_ct_lcmh_h_cluster, 4))

cluster_solution <- get_cluster_solution(f0_di_ct_lcmh_h_kmeans)
compare_cluster(cluster_solution, 'cluster4')
```
```{r}
# examine mismathes
f0_di_ct_lcmh_h_kmeans %>% filter(sandhi_tone == 'HMML' & cluster4 == 'C')
```



try doing k-means for the whole disyllabic citation dataset
```{r}
f0_di_ct_lcmh_kmeans <- f0_di_ct_lcmh %>% 
  filter(!sandhi_tone %in% c(NA, 'outlier')) %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(normtime, norm_f0)

f0_di_ct_lcmh_cluster <- k_means(f0_di_ct_lcmh_kmeans)
kml(f0_di_ct_lcmh_cluster, nbClusters = 2:10) 
plot(f0_di_ct_lcmh_cluster, 7, parTraj=parTRAJ(col="clusters"))

f0_di_ct_lcmh_kmeans <- f0_di_ct_lcmh_kmeans %>% 
  mutate(cluster7 = getClusters(f0_di_ct_lcmh_cluster, 7))
```

Mapping between human and machine clustering
```{r}
cluster_solution <- get_cluster_solution(f0_di_ct_lcmh_kmeans)
compare_cluster(cluster_solution, 'cluster7')
```


