---
title: "Disyllabic Lexical Compound citation (broad focus) sandhi: initial inspection"
output: html_document
date: "Last updated: 2023-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(plotly)
library(gridExtra) 
library(ggpubr)
library(writexl)
library(readxl)
```

# Data preparations  
**Construct data frame ** 
```{r data-construction}
load("XSTSF_production.RData")
f0_di <- f0_all_pre %>% filter(diortri == 'di') 
f0_di_ct <- f0_di %>% filter(focus_condition == 'ct')
```

**A function to plot & save f0 contours**
```{r function}
draw_by <- function(dataframe, x, y){
  p <- dataframe %>% 
      ggplot(aes(x=time, y=norm_f0, group=interaction(syllable_no, ind_no), color=citation_no, linetype=citation_no, text = paste('speaker: ', speaker, '\ncitation tone: ', citation_tone, '\ncitation no:', citation_no, '\ntoken: ', token)))+
      geom_line()+
      ylim(-3, 3)+
    {if (missing(y)) {facet_wrap(as.formula(paste("~", x)), ncol = 2, labeller = label_both)}
        else {facet_grid(as.formula(paste(y, "~", x)), labeller = label_value)}}+
      theme_bw()+
      theme(panel.spacing.y = unit(0.02, "cm", data = NULL),
            text = element_text(size = 10)) 
  p
}
```

**Plot & save plots**
```{r di-ct-plot}
# grouped by citation tone combination
for (var in unique(f0_di_ct$syntax_iniTone)) {
  sub_df <- f0_di_ct %>% filter(syntax_iniTone == var)
  assign(paste0('ct_', var, '_byCT'), draw_by(sub_df, 'citation_tone'))
} 

# grouped by speaker
for (var in unique(f0_di_ct$syntax_iniTone)) {
  sub_df <- f0_di_ct %>% filter(syntax_iniTone == var)
  assign(paste0('ct_', var, '_byS'), draw_by(sub_df, 'speaker'))
} 
```

<br>
<br>

# Contour visualisation: initial inspection  
### HTs (HH/HL shang)-initial Lexical Compounds: 

```{r}
unique(f0_di_ct[f0_di_ct$syntax_iniTone == 'L_HTs', ]$token)
```

```{r di-ct-HTs, out.width='100%', out.height='800px'}
p1 <- ggplotly(ct_L_HTs_byCT, tooltip = c('text', 'x')) 
p2 <- ggplotly(ct_L_HTs_byS, tooltip = c('text', 'x')) 

subplot(p1, p2) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.1))
```


<br>

### HTp (HH/HL ping)-initial Lexical Compounds:
```{r}
unique(f0_di_ct[f0_di_ct$syntax_iniTone == 'L_HTp', ]$token)
```

```{r di-ct-HTp, out.width='100%', out.height='800px'}
p1 <- ggplotly(ct_L_HTp_byCT, tooltip = c('text', 'x'))
p2 <- ggplotly(ct_L_HTp_byS, tooltip = c('text', 'x'))

subplot(p1, p2) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.1))
```

<br>

### LT (LHL/LH)-initial Lexical Compounds: 
```{r di-ct-LT, out.width='100%', out.height='800px'}
p1 <- ggplotly(ct_L_LT_byCT, tooltip = c('text', 'x'))
p2 <- ggplotly(ct_L_LT_byS, tooltip = c('text', 'x'))

subplot(p1, p2) %>% layout(legend = list(orientation = "h", x = 0.4, y = -0.1))
```

