---
title: "Sandhi patterns after categorisation"
output: html_document
date: "Last updated: 2023-10-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(ggrepel)
library(ggpubr)
library(RColorBrewer)
```

## Data preparation
Load saved data and perform initial data processing 
```{r}
load("XSTSF_production.RData")
label_sandhi <- read.csv('raw_data/sandhi_label.csv', na.strings = '') 
f0_all_sandhi <- f0_all_pre %>% 
  select(!sandhi_tone) %>% 
  left_join(label_sandhi[, c('ind_no', 'sandhi_tone', 'sandhi_tone_var', 'diortri')], by = c('diortri', 'ind_no'))
```

Functions to process and plot data
```{r}
# a function to filter the data frame
get_df <- function(x, y){
  df<- f0_all_sandhi %>% 
    filter(syntax_iniTone == x & focus_condition == y) %>% 
    mutate(sandhi_tone_var = case_when(is.na(sandhi_tone_var) == TRUE ~ sandhi_tone,
                                     .default = sandhi_tone_var))
  return(df)
}

# a function to visualise individual f0 contours in groups
draw_by <- function(dataframe, x, y){
  p <- dataframe %>% 
      ggplot(aes(x=time, y=norm_f0, group=interaction(syllable_no, ind_no), color=citation_no, linetype=citation_no, text = paste('speaker: ', speaker, '\ncitation tone: ', citation_tone, '\ncitation no:', citation_no, '\ntoken: ', token)))+
      geom_line()+
      ylim(-3, 3)+
    {if (missing(y)) {facet_wrap(as.formula(paste("~", x)), ncol = 2, labeller = label_both)}
        else {facet_grid(as.formula(paste(y, "~", x)), labeller = label_value)}}+
      theme_bw()+
      theme(panel.spacing.y = unit(0.02, "cm", data = NULL),
            text = element_text(size = 10)) 
  return(p)
}

# a function to calculate and visualise average f0 contours
std <- function(x) sd(x)/sqrt(length(x))

f0_mean <- function(df, x){
  df <- df %>% 
    # filter data frame & update sandhi labels
    filter(sandhi_tone != 'outlier' & is.na(sandhi_tone) == FALSE) %>% 
    # create a group variable
    unite('groupvar', syllable_no, {{x}}, sep = '_', remove = FALSE) %>% 
    # calculate mean f0
    group_by(groupvar, time, syllable_no, {{x}}) %>% 
    summarise(meanf0 = mean(norm_f0),
              se = std(norm_f0),
              count = n()) %>% 
    # add count
    mutate(count_text = ifelse(time == 20, paste('n=', count, sep = ''), NA)) 
  
  p <- df %>% 
    ggplot(aes(x = as.numeric(time), y = meanf0, color = {{x}}, linetype = {{x}}, group = groupvar))+
    geom_errorbar(aes(ymin=meanf0-se, ymax=meanf0+se, width=.1))+
    geom_line(size = 1.3)+
    geom_point()+
    ylim(-3, 3)+
    scale_color_manual(labels = c('sandhi1', 'sandhi2', 'sandhi3', 'sandhi4'), 
                       values = c('#56B4E9', '#e98b56', '#56e98b', '#e956b4'))+
    scale_linetype_manual(labels = c('sandhi1', 'sandhi2', 'sandhi3', 'sandhi4'), 
                          values = c('solid', 'dashed', 'dotdash', 'dotted'))+
    geom_text_repel(data = subset(df, is.na(count_text) == FALSE), 
                    aes(label = count_text), size = 5, family = 'Times New Roman')+
    theme_minimal()+
    theme(legend.position = c(0.12, 0.85), 
        axis.text = element_text(size=15),
        legend.title = element_text(size = 15),
        legend.text = element_text(size = 15),
        text = element_text(family = 'Times New Roman'))+ 
    rremove("ylab")+rremove("xlab")+
    theme(legend.title=element_blank())
  
  return(p)
}

# a function to calculate the counts
count_plot <- function(df, x, y){
  df_count <- df %>% 
    filter(is.na(sandhi_tone) == FALSE & time == 1) %>%
    group_by({{x}}, {{y}}) %>% 
    summarise(count = n())
  
  p <- ggplot(df_count, 
              aes(x = {{x}}, y = count, fill = {{y}}, label = count))+
    geom_bar(stat = 'identity')+
    geom_text(size = 3, position = position_stack(vjust = 0.5))+
    theme_minimal()+
    scale_fill_brewer(palette = "RdYlBu")
  
  return(p)
}
```

## Data visualisation  
### HH-*shang*-initial lexical compounds
Individual f0 contours
```{r, fig.show='hold', out.width='50%', out.height = '400px', warning=FALSE, message=FALSE}
f0_di_L_HTs_ct <- get_df('L_HTs', 'ct')
draw_by(f0_di_L_HTs_ct, 'sandhi_tone')
draw_by(f0_di_L_HTs_ct, 'sandhi_tone_var')
```

Mean f0 contours
```{r, fig.show='hold', out.width='50%', warning=FALSE, message=FALSE}
f0_mean(f0_di_L_HTs_ct, sandhi_tone) 
f0_mean(f0_di_L_HTs_ct, sandhi_tone_var)
```

Distribution of sandhi output variations 
```{r, fig.show='hold', out.width='50%', warning=FALSE, message=FALSE}
count_plot(f0_di_L_HTs_ct, speaker, sandhi_tone)
count_plot(f0_di_L_HTs_ct, citation_tone, sandhi_tone)
```


<br>
<br>

## Tone clustering vs. manual categorisation: trial
```{r, eval=FALSE}
# try contour clustering
label_sandhi <- read.csv('sandhi_label.csv', na.strings = '')

f0_di_ct <- f0_di_ct %>% 
  select(!(sandhi_tone)) %>% 
  left_join(label_sandhi[, c('ind_no', 'focus_condition', 'sandhi_tone', 'sandhi_tone_var', 'diortri')], by = c('diortri', 'ind_no', 'focus_condition'))

f0_di_L_M_ct <- f0_di_ct %>% 
  filter(syntax %in% c('L', 'M')) %>% 
  mutate(sandhi_tone_var = case_when(is.na(sandhi_tone_var) == TRUE ~ sandhi_tone,
                                     .default = sandhi_tone_var))

test <- f0_di_L_M_ct %>% 
  select(speaker, ind_no, time, norm_f0) %>% 
  mutate(start = 1,
         end = 21,
         step = rep(2:21, times = nrow(f0_di_L_M_ct)/20), 
         jumpkilleffect = 1) %>% 
  rename(filename = speaker,
         interval_label = ind_no, 
         stepnumber = time,
         f0 = norm_f0)
write.csv(test, 'clustering/test.csv', row.names = FALSE)

# compare the clusters with manual categorizations
sandhi_cluster <- read.csv('clustering/saved/data_wide_4.csv')
sandhi_cluster <- sandhi_cluster[, c('interval_label', 'cluster')]
  
f0_di_L_M_ct <- f0_di_L_M_ct %>% 
  left_join(sandhi_cluster, by = c('ind_no' = 'interval_label')) %>% 
  filter(time == 1)
```




