---
title: "Trisyllabic sandhi in the Xiangshan dialect"
author: "Yibing Shi"
date: "2024-10-17"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(gridExtra) 
library(ggthemes)
library(viridis)
library(plotly)
library(ggrepel)
library(kml)
library(nnet)    # For multinomial logistic regression
library(glmnet)  # For penalized regression
```

# Data preparations  
```{r data-construction, cache=FALSE}
load("XSTSF_production.RData")
source('functions.R')
```

datasets
```{r data-construction, cache=FALSE}
f0_all_ct <- f0_all_pre %>% filter(focus_condition == 'ct' ) %>% 
  group_by(speaker) %>% 
  mutate(norm_f0 = scale(log(f0))) %>% 
  ungroup() %>% 
  mutate(
    time = as.numeric(time),
    syllable_no = case_when(
    time > 0 & time < 11 ~ 1,
    time > 10 & time < 21 ~ 2,
    time > 20 & time < 31 ~ 3
  ),
  sync_tone1 = ifelse(sync_tone1 == 'RF', 'LHL', sync_tone1),
  sync_tone2 = ifelse(sync_tone2 == 'RF', 'LHL', sync_tone2),
  sync_tone3 = ifelse(sync_tone3 == 'RF', 'LHL', sync_tone3))

f0_tri_ct <- f0_all_ct %>% filter(diortri == 'tri' & sandhi_tone != 'outlier')  
f0_tri_ct_yp <- f0_tri_ct %>% filter(hist_tone1 == 'yinping')
```

functions
```{r}
distri_prop <- function(df, x, y, z = NULL) {
  x <- rlang::enquo(x)
  y <- rlang::enquo(y)
  z <- rlang::enquo(z)

# Define a custom color palette for each sync_tone level
  custom_palette <- c(
    "HH" = "#4477AA",  
    "HL" = "#CC6677",
    "LHL" = "#DDCC77",
    "LH" = "#117733",
    "HHL" = "#4477AA",
    "HLM" = "#CC6677",
    "HML" = "#117733",
    "MMH" = "purple"
  )

# Calculate counts
    df1 <- df %>%
      filter(time == 1) %>%
      group_by(!!x, !!y, !!z) %>%
      count() %>%
      ungroup() %>%
      group_by(!!x, !!z) %>%
      mutate(count = sum(n),
             prop = n / count) %>%
      ungroup()

# Plot data
    p <- ggplot(df1, aes(x = !!x, y = prop, fill = !!y, 
                         label = ifelse(prop > 0.15, paste0(round(prop * 100), '%\n(', n, ')'),
                                        paste0(round(prop * 100), '%')))) + 
      geom_bar(position = "stack", stat = "identity") +
      geom_text(size = 5, family = 'Times New Roman', position = position_stack(vjust = 0.5)) +
      scale_fill_manual(values = custom_palette) +
      theme_classic() +
      ylab('frequency proportion') +
      theme(text = element_text(size = 20, family = 'Times New Roman'),
            axis.text.x = element_text(angle = 45, hjust = 1)) +
      facet_wrap(vars(!!z), scales = "free_x") +
      scale_y_continuous(labels = scales::percent)
    
  return(p)
} 


distri_prop2 <- function(df, x, y) {
  x <- rlang::enquo(x)
  y <- rlang::enquo(y)
  
  # Define a custom color palette for each sync_tone level
  custom_palette <- c(
    "HH" = "#4477AA",  
    "HL" = "#CC6677",
    "LHL" = "#DDCC77",
    "LH" = "#117733",
    "HHL" = "#4477AA",
    "HLM" = "#CC6677",
    "HML" = "#117733",
    "MMH" = "purple"
  )
  
  # Group by x, y
  df1 <- df %>%
    filter(time == 1) %>%
    group_by(!!x, !!y) %>%
    count() %>%
    ungroup() %>%
    group_by(!!x) %>%
    mutate(count = sum(n),
           prop = n / count) %>%
    ungroup()
  
  p <- ggplot(df1, aes(x = !!x, y = prop, fill = !!y, 
                       label = ifelse(prop > 0.15, paste0(round(prop * 100), '%\n(', n, ')'),
                                        paste0(round(prop * 100), '%')))) + 
    geom_bar(position = "stack", stat = "identity") +
    geom_text(size = 5, family = 'Times New Roman', position = position_stack(vjust = 0.5)) +
    scale_fill_manual(values = custom_palette) +
    theme_minimal() +
    labs(fill = 'sandhi category') +
    ylab('frequency proportion') +
    theme(text = element_text(size = 20, family = 'Times New Roman'))+ 
    scale_y_continuous(labels = scales::percent)
  
  return(p)
}

```


# yinping-initial
```{r}
unique(f0_tri_ct_yp$sandhi_tone)

p_cluster(f0_tri_ct_yp, sandhi_tone)
```

## k-means clustering
```{r}
# data preparation
f0_tri_ct_yp_kmeans <- f0_tri_ct_yp %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(time, norm_f0)

# k-means clustering
cluster_model <- k_means_clustering(f0_tri_ct_yp_kmeans)
kml(cluster_model, nbClusters = 2:10) 
kml::plot(cluster_model, 2, parTraj=parTRAJ(col="clusters"))
kml::plot(cluster_model, 3, parTraj=parTRAJ(col="clusters"))
kml::plot(cluster_model, 4, parTraj=parTRAJ(col="clusters"))
kml::plot(cluster_model, 5, parTraj=parTRAJ(col="clusters"))
plotAllCriterion(cluster_model)


# get cluster results
f0_tri_ct_yp_kmeans <- f0_tri_ct_yp_kmeans %>% 
  mutate(cluster3 = getClusters(cluster_model, 3),
         cluster5 = getClusters(cluster_model, 5))

f0_tri_ct_yp_kmeans <- wide_to_long(f0_tri_ct_yp_kmeans) %>% 
  mutate(syllable_no = ifelse(time < 11, '1', 
                              ifelse(time < 21, '2', '3'))) %>% 
  mutate(cluster3_reorder = case_when(cluster3 == 'B' ~ 'A',
                                      cluster3 == 'C' ~ 'B',
                                      cluster3 == 'A' ~ 'C'),
         cluster5_reorder = case_when(cluster5 == 'C' ~ 'A',
                                      cluster5 == 'A' ~ 'B',
                                      cluster5 == 'D' ~ 'C',
                                      cluster5 == 'E' ~ 'D',
                                      cluster5 == 'B' ~ 'E'))
```

cluster visualisation
```{r warning=FALSE, message=FALSE}
f0_tri_ct_yp_kmeans <- f0_tri_ct_yp_kmeans %>% 
  mutate(cluster3_reorder = case_when(cluster3 == 'B' ~ 'A',
                                      cluster3 == 'C' ~ 'B',
                                      cluster3 == 'A' ~ 'C'),
         cluster5_reorder = case_when(cluster5 == 'C' ~ 'A',
                                      cluster5 == 'A' ~ 'B',
                                      cluster5 == 'D' ~ 'C',
                                      cluster5 == 'E' ~ 'D',
                                      cluster5 == 'B' ~ 'E'))

p_kmeans3 <- p_cluster(f0_tri_ct_yp_kmeans, cluster3_reorder);p_kmeans3
p_kmeans5 <- p_cluster(f0_tri_ct_yp_kmeans, cluster5_reorder);p_kmeans5
```
heatmap distribution
```{r message=FALSE, warning=FALSE}
heatmap_df <- heatmap_data(f0_tri_ct_yp_kmeans, cluster3_reorder) 
p_htmap3 <- compare_cluster(heatmap_df, 'cluster3_reorder'); p_htmap3

heatmap_df <- heatmap_data(f0_tri_ct_yp_kmeans, cluster5_reorder) 
p_htmap5 <- compare_cluster(heatmap_df, 'cluster5_reorder'); p_htmap5
```



## Distribution analysis

monosyllabic tones
```{r}
f0_tri_ct_yp %>%
  distri_prop(hist_tone1, sync_tone1, syntax)+
  xlab("historical tone")+
  labs(fill = "synchronic tone")
  
f0_tri_ct_yp %>%
  filter(startsWith(hist_tone2, "yin")) %>%
  distri_prop(hist_tone2, sync_tone2, syntax)+
  xlab("historical tone")+
  labs(fill = "synchronic tone")

f0_tri_ct_yp %>%
  filter(startsWith(hist_tone3, "yin")) %>%
  distri_prop(hist_tone3, sync_tone3, syntax)+
  xlab("historical tone")+
  labs(fill = "synchronic tone")

f0_tri_ct_yp %>%
  filter(startsWith(hist_tone2, "yang")) %>%
  distri_prop(hist_tone2, sync_tone2, syntax)+
  xlab("historical tone")+
  labs(fill = "synchronic tone")

f0_tri_ct_yp %>%
  filter(startsWith(hist_tone3, "yang")) %>%
  distri_prop(hist_tone3, sync_tone3, syntax)+
  xlab("historical tone")+
  labs(fill = "synchronic tone")
```
trisyllabic sandhi patterns
```{r}
f0_tri_ct_yp_12mh <- f0_tri_ct_yp %>% filter(syntax == "1+2MH")
f0_tri_ct_yp_21ll <- f0_tri_ct_yp %>% filter(syntax == "2+1LL")
f0_tri_ct_yp_21vl <- f0_tri_ct_yp %>% filter(syntax == "2+1VL")

# 1+2MH
distri_prop2(f0_tri_ct_yp_12mh, sync_tone1, sandhi_tone)
#distri_prop2(f0_tri_ct_yp_12mh, hist_tone2, sandhi_tone)
#distri_prop2(f0_tri_ct_yp_12mh, hist_tone3, sandhi_tone)

f0_tri_ct_yp_12mh %>% 
 #filter(sync_tone1 == 'HL') %>% 
  distri_prop(hist_tone3, sandhi_tone, hist_tone2)


# 2+1LL
distri_prop2(f0_tri_ct_yp_21ll, sync_tone1, sandhi_tone)
distri_prop(f0_tri_ct_yp_21ll, hist_tone3, sandhi_tone, hist_tone2)


# 2+1VL
#distri_prop2(f0_tri_ct_yp_21vl, sync_tone1, sandhi_tone)
distri_prop(f0_tri_ct_yp_21vl, hist_tone3, sandhi_tone, hist_tone2)
```


build model
```{r}
f0_tri_ct_yp <- f0_tri_ct_yp %>% 
  mutate(sandhi_tone = as.factor(sandhi_tone),
         sync_tone1 = as.factor(sync_tone1),
         hist_tone2 = as.factor(hist_tone2),
         hist_tone3 = as.factor(hist_tone3),
         syntax = as.factor(syntax),
         speaker = as.factor(speaker))

model <- multinom(sandhi_tone ~ sync_tone1 + hist_tone2 + hist_tone3 + syntax + speaker, data = f0_tri_ct_yp)
summary(model)

model_a1 <- multinom(sandhi_tone ~ sync_tone1 + hist_tone2 + hist_tone3 + speaker*syntax, data = f0_tri_ct_yp)
anova(model_a1, model, test = "Chisq")

model_1 <- multinom(sandhi_tone ~ hist_tone2 + hist_tone3 + syntax + speaker, data = f0_tri_ct_yp)
anova(model_1, model, test = "Chisq")

model_2 <- multinom(sandhi_tone ~ sync_tone1 + hist_tone3 + syntax + speaker, data = f0_tri_ct_yp)
anova(model_2, model, test = "Chisq")

model_3 <- multinom(sandhi_tone ~ sync_tone1 + hist_tone2 + syntax + speaker, data = f0_tri_ct_yp)
anova(model_3, model, test = "Chisq")

model_4 <- multinom(sandhi_tone ~ sync_tone1 + hist_tone2 + hist_tone3 + syntax, data = f0_tri_ct_yp)
anova(model_4, model, test = "Chisq")

model_5 <- multinom(sandhi_tone ~ sync_tone1 + hist_tone2 + hist_tone3 + speaker, data = f0_tri_ct_yp)
anova(model_5, model, test = "Chisq")
```

## yinshang-initial