---
title: "Analysis of disyllabic Lexical Compound & Modifier-Head phrases citation tone
  sandhi patterns in Xiangshan"
output: html_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(gridExtra) 
library(ggthemes)
library(viridis)
library(plotly)
library(ggrepel)
library(kml)
```

# Data preparations  
```{r}
# paths
current_dir <- getwd()
plot_dir <- file.path(current_dir, "plots")

# load data & functions
load("XSTSF_production.RData")
source('functions.R')
```


```{r data-construction, cache=FALSE}
f0_all_ct <- f0_all_pre %>% filter(focus_condition == 'ct' ) %>% 
  group_by(speaker) %>% 
  mutate(norm_f0 = scale(log(f0))) %>% 
  ungroup()

f0_di_ct_lcmh <- f0_all_ct %>% 
  filter(syntax %in% c('L', 'M') & diortri == 'di') %>% 
  mutate(sandhi_tone = case_when(sandhi_tone == 'HLLM' ~ 'HMML',
                                 sandhi_tone == 'LLRF' ~ 'LLHL', 
                                 sandhi_tone == 'LLLM' ~ 'LLLH',
                                 sandhi_tone == 'LMML' ~ 'LHML',
                                 .default = sandhi_tone)) %>% 
  filter(!ind_no %in% c('S2_1_ct', 'S2_11_ct', 'S2_27_ct', 'S3_5_ct', 'S3_19_ct', 'S5_27_ct',
                        'S2_44_ct', 'S3_37_ct', 'S3_44_ct', 'S6_16_ct', 'S6_31_ct', 'S6_39_ct', 'S7_33_ct')) %>% 
  filter(is.na(sandhi_tone) == FALSE) 
  
f0_di_ct_lcmh_l <- f0_di_ct_lcmh %>% 
  filter( grepl('^[LR]', sync_tone1)) %>% 
  mutate(sync_tone1 = ifelse(sync_tone1 == 'RF', 'LHL', sync_tone1),
         sync_tone2 = ifelse(sync_tone2 == 'RF', 'LHL', sync_tone2)) %>% 
  mutate(sync_tone1 = factor(sync_tone1, levels = c('HH', 'HL', 'LH', 'LHL')),
         sync_tone2 = factor(sync_tone2, levels = c('HH', 'HL', 'LH', 'LHL'))) %>% 
  mutate(hist_tone1 = factor(hist_tone1, levels = c('yangping', 'yangshang')),
         hist_tone2 = factor(hist_tone2, levels = c('yinping', 'yinshang', 'yinqu', 'yangping', 'yangqu'))) %>%
  mutate(sandhi_tone = factor(sandhi_tone, levels = c('LHML', 'LLLH', 'LLHH', 'LLHL')))

f0_di_ct_lc_l <- f0_di_ct_lcmh_l %>% filter(syntax == 'L')
f0_di_ct_mh_l <- f0_di_ct_lcmh_l %>% filter(syntax == 'M')

f0_di_ct_lcmh_lp <- f0_di_ct_lcmh_l %>% filter(hist_tone1 == 'yangping')
f0_di_ct_lcmh_ls <- f0_di_ct_lcmh_l %>% filter(hist_tone1 == 'yangshang')
```


# Initial data inspection

```{r fig.height=8}
# yinping-initial LC & MH
ggplotly(draw_by(f0_di_ct_lcmh_hp, 'speaker'), tooltip = c('text', 'x'))

# yinshang-initial LC & MH
ggplotly(draw_by(f0_di_ct_lcmh_hs, 'speaker'), tooltip = c('text', 'x'))

# yangping-initial LC & MH
ggplotly(draw_by(f0_di_ct_lcmh_lp, 'speaker'), tooltip = c('text', 'x'))

# yangshang-initial LC & MH
ggplotly(draw_by(f0_di_ct_lcmh_ls, 'speaker'), tooltip = c('text', 'x'))
```


# Auditory categorisation

```{r, warning=FALSE, message=FALSE}
unique(f0_di_ct_lcmh_l$sandhi_tone) # check the labels

p_cluster(f0_di_ct_lcmh_l, sandhi_tone)
ggsave(filename = file.path(plot_dir, "l_human.jpeg"),width = 8, height = 4)
```


# k-means clustering 
```{r message=FALSE, warning=FALSE}
# data preparation
f0_di_ct_lcmh_l_kmeans <- f0_di_ct_lcmh_l %>% 
  select(-diortri, -syllable_no, -focus_no, -f0) %>% 
  spread(time, norm_f0)

# k-means clustering
cluster_model <- k_means_clustering(f0_di_ct_lcmh_l_kmeans)
kml(cluster_model, nbClusters = 2:10) 
kml::plot(cluster_model, 3, parTraj=parTRAJ(col="clusters"))
kml::plot(cluster_model, 4, parTraj=parTRAJ(col="clusters"))
plotAllCriterion(cluster_model)

# get cluster results
f0_di_ct_lcmh_l_kmeans <- f0_di_ct_lcmh_l_kmeans %>% 
  mutate(cluster4 = getClusters(cluster_model, 4),
         cluster3 = getClusters(cluster_model, 3)) 
 # mutate(sandhi_tone = ifelse(cluster4 == 'C' & sandhi_tone == 'LLLM', 'LLRF', sandhi_tone))

f0_di_ct_lcmh_l_kmeans <- wide_to_long(f0_di_ct_lcmh_l_kmeans) %>% 
  mutate(syllable_no = ifelse(time < 11, '1', '2')) %>% 
   mutate(cluster3_reorder = case_when(cluster3 == 'A' ~ 'B',
                                      cluster3 == 'B' ~ 'C',
                                      cluster3 == 'C' ~ 'A'),
         cluster4_reorder = case_when(cluster4 == 'A' ~ 'C',
                                      cluster4 == 'B' ~ 'B',
                                      cluster4 == 'C' ~ 'D',
                                      cluster4 == 'D' ~ 'A'))
```

```{r warning=FALSE, message=FALSE}
p_kmeans3 <- p_cluster(f0_di_ct_lcmh_l_kmeans, cluster3_reorder);p_kmeans3
p_kmeans4 <- p_cluster(f0_di_ct_lcmh_l_kmeans, cluster4_reorder);p_kmeans4
```


```{r message=FALSE, warning=FALSE}
# heatmap distribution
heatmap_df <- heatmap_data(f0_di_ct_lcmh_l_kmeans, cluster3_reorder) 
p_htmap3 <- compare_cluster(heatmap_df, 'cluster3_reorder'); p_htmap3

heatmap_df <- heatmap_data(f0_di_ct_lcmh_l_kmeans, cluster4_reorder) 
p_htmap4 <- compare_cluster(heatmap_df, 'cluster4_reorder'); p_htmap4
```

combinations of plots
```{r}
ggarrange(p_kmeans3, p_htmap3, widths = c(1.4, 1))
ggsave(filename = file.path(plot_dir, "l_kmeans3.jpeg"),width = 12, height = 4, dpi = 300)

ggarrange(p_kmeans4, p_htmap4, widths = c(1.4, 1))
ggsave(filename = file.path(plot_dir, "l_kmeans4.jpeg"),width = 12, height = 4, dpi = 300)
```

Examine mismatches
```{r}
f0_di_ct_lcmh_l_kmeans <- f0_di_ct_lcmh_l_kmeans %>% 
  mutate(sub_cluster = paste0(sandhi_tone, '_', cluster4_reorder))
cluster_lllm <- f0_di_ct_lcmh_l_kmeans %>% filter(sandhi_tone == 'LLLH')
p_cluster(cluster_lllm, sub_cluster)
ggsave(filename = file.path(plot_dir, "l_mismatch.jpeg"),width = 8, height = 4)
```





# Distribution analysis  

```{r}
# monosyllabic citation tones
distri_prop2(f0_di_ct_lcmh_l, hist_tone1, sync_tone1)+
  xlab('initial syllable historical tone')+labs(fill = 'synchronic tone')
ggsave(filename = file.path(plot_dir, "l_tone1.jpeg"),width = 7, height = 3.5, dpi = 300)

distri_prop2(f0_di_ct_lcmh_l, hist_tone2, sync_tone2)+
  xlab('second syllable historical tone')+labs(fill = 'synchronic tone')
ggsave(filename = file.path(plot_dir, "l_tone2.jpeg"),width = 8, height = 4, dpi = 300)
```

```{r}
# by initial tone
distri_prop2(f0_di_ct_lcmh_l, hist_tone1, sandhi_tone)+xlab('initial tone')
ggsave(filename = file.path(plot_dir, "l_dist_tone1.jpeg"),width = 7, height = 3.5, dpi = 300)
```

```{r}
# by second tone
distri_prop(f0_di_ct_lcmh_lp, sync_tone2, sandhi_tone, speaker)
distri_prop(f0_di_ct_lcmh_hs, sync_tone2, sandhi_tone, speaker)

# yinping-initial
p_tone2lph <- distri_prop2(f0_di_ct_lcmh_lp, hist_tone2, sandhi_tone)+
  xlab('2nd.syllable.hist.tone');p_tone2lph
p_tone2lps <- distri_prop2(f0_di_ct_lcmh_lp, sync_tone2, sandhi_tone)+
  xlab('2nd.syllable.sync.tone');p_tone2lps
p_tone2lp <- ggarrange(p_tone2lph+rremove("ylab"), 
          p_tone2lps+rremove("ylab"),
          common.legend = TRUE, legend = "right");p_tone2lp
p_tone2lp <- annotate_figure(p_tone2lp, 
            left = text_grob("frequency proportion", 
                             rot = 90, vjust = 1, size = 20,
                             family = 'Times New Roman')); p_tone2lp

ggsave(filename = file.path(plot_dir, "l_dist_tone2p.jpeg"),width = 12, height = 4, dpi = 300)

# yinshang-initial
p_tone2lsh <- distri_prop2(f0_di_ct_lcmh_ls, hist_tone2, sandhi_tone)+
  scale_fill_manual(values = c("#CC6677", "#DDCC77", "#117733"))+
  xlab('2nd.syllable.hist.tone'); p_tone2hsh
p_tone2lss <- distri_prop2(f0_di_ct_lcmh_ls, sync_tone2, sandhi_tone)+
  scale_fill_manual(values = c("#CC6677", "#DDCC77", "#117733"))+
  xlab('2nd.syllable.sync.tone'); p_tone2hss
p_tone2ls <- ggarrange(p_tone2lsh+rremove("ylab"), 
          p_tone2lss+rremove("ylab"),
          common.legend = TRUE, legend = "right")
p_tone2ls <- annotate_figure(p_tone2ls, 
            left = text_grob("frequency proportion", 
                             rot = 90, vjust = 1, size = 20,
                             family = 'Times New Roman')); p_tone2ls
ggsave(filename = file.path(plot_dir, "l_dist_tone2s.jpeg"),width = 11, height = 4, dpi = 300)
```

```{r, out.width='100%'}
# by speaker
distri_prop(f0_di_ct_lcmh_l, speaker, sandhi_tone, hist_tone1)
ggsave(filename = file.path(plot_dir, "l_dist_speaker.jpeg"),width = 10, height = 5, dpi = 300)
```

```{r, out.width='100%'}
# first tone and syntax
distri_prop(f0_di_ct_lcmh_l, syntax, sandhi_tone, hist_tone1)
ggsave(filename = file.path(plot_dir, "l_dist_syntax.jpeg"),width = 7, height = 3.5, dpi = 300)
```


# Gradience

```{r}
f0_di_ct_lcmh_l_llhh <- filter(f0_di_ct_lcmh_l, sandhi_tone == 'LLHH') %>% 
  mutate(sandhi_tone = paste0(sandhi_tone, '_', hist_tone1))
p_cluster(f0_di_ct_lcmh_l_llhh, sandhi_tone)
ggsave(filename = file.path(plot_dir, "l_llhh.jpeg"),width = 8, height = 4)
```

## Group-by different factors

```{r, warning=FALSE, message=FALSE}
# second tone [synchronic] & syntax
p_sub_cluster(f0_di_ct_lcmh_l, sync_tone2, sandhi_tone)

# LLLM
f0_di_ct_lp_lllm <- f0_di_ct_lcmh_lp %>% filter(sandhi_tone == 'LLLH')
p_cluster(f0_di_ct_lp_lllm, sync_tone2, 'sandhi_tone')
p_sub_cluster(f0_di_ct_lp_lllm, sync_tone2, sandhi_tone)

# LLLM: LC
f0_di_ct_lc_lp_lllm <- f0_di_ct_lcmh_lp %>% filter(sandhi_tone == 'LLLM' & syntax == 'L')
p_sub_cluster(f0_di_ct_lc_lp_lllm, sync_tone2, sandhi_tone)

# LLLM: AN
f0_di_ct_mh_lp_lllm <- f0_di_ct_lcmh_lp %>% filter(sandhi_tone == 'LLLM' & syntax == 'M')
p_sub_cluster(f0_di_ct_mh_lp_lllm, sync_tone2, sandhi_tone)


# yangping & yangshang
p_sub_cluster(f0_di_ct_lcmh_hp, sync_tone2, sandhi_tone)
p_sub_cluster(f0_di_ct_lcmh_lp, sync_tone2, sandhi_tone)
p_sub_cluster(f0_di_ct_lp_lllm, sync_tone2)
p_sub_cluster(f0_di_ct_lp_lllm, sync_tone2, syntax)
p_sub_cluster(f0_di_ct_lcmh_ls, sync_tone2, sandhi_tone)

f0_di_ct_lp_lllm %>% filter(sync_tone2 == 'HL')
```





