---
title: "Comparisons of contours between H- & L-register-initial datasets"
output: html_document
date: "2024-05-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(gridExtra) 
library(ggthemes)
library(viridis)
library(plotly)
library(ggrepel)
```

# Data preparations  

```{r data-construction, cache=FALSE}
load("XSTSF_production.RData")
source('functions.R')

f0_all_ct <- f0_all_pre %>% filter(focus_condition == 'ct' ) %>% 
  group_by(speaker) %>% 
  mutate(norm_f0 = scale(log(f0))) %>% 
  ungroup()

f0_di_ct_lcmh <- f0_all_ct %>% 
  filter(syntax %in% c('L', 'M') & diortri == 'di') %>% 
  mutate(sandhi_tone = case_when(sandhi_tone == 'HLLM' ~ 'HMML',
                                 sandhi_tone == 'LLHL' ~ 'LLRF', 
                                 .default = sandhi_tone)) %>% 
  filter(!ind_no %in% c('S2_1_ct', 'S2_11_ct', 'S2_27_ct', 'S3_5_ct', 'S3_19_ct', 'S5_27_ct')) %>% 
  filter(is.na(sandhi_tone) == FALSE) 
  
f0_di_ct_lcmh_h <- f0_di_ct_lcmh %>% filter( grepl('^H', sync_tone1))
f0_di_ct_lcmh_l <- f0_di_ct_lcmh %>% filter( grepl('^[LR]', sync_tone1)) 

f0_di_ct_lcmh_p_fall <- f0_di_ct_lcmh %>% filter(hist_tone1 %in% c('yinping', 'yangping') &
                                              sandhi_tone %in% c('HMML', 'LHML'))
f0_di_ct_lcmh_p_rise <- f0_di_ct_lcmh %>% filter(hist_tone1 %in% c('yinping', 'yangping') &
                                              sandhi_tone %in% c('MMMH', 'LLLH', 'LLHH'))
f0_di_ct_lcmh_s_rf <- f0_di_ct_lcmh %>% filter((hist_tone1 %in% c('yinshang', 'yangshang') &
                                              sandhi_tone %in% c('MHHL', 'LLHL'))) 
f0_di_ct_lcmh_s_rise <- f0_di_ct_lcmh %>% filter((hist_tone1 %in% c('yinshang', 'yangshang') &
                                              sandhi_tone %in% c('HHHH', 'LLHH'))) 
unique(f0_di_ct_lcmh_s_rise$sandhi_tone)
```

```{r, warning=FALSE, message=FALSE}
p_fall <- p_cluster(f0_di_ct_lcmh_p_fall, sandhi_tone)
p_rise <-p_cluster(f0_di_ct_lcmh_p_rise, sandhi_tone)
p_rf <-p_cluster(f0_di_ct_lcmh_s_rf, sandhi_tone)
p_level <-p_cluster(f0_di_ct_lcmh_s_rise, sandhi_tone)

p_all <- ggarrange(p_fall+ rremove("ylab") + rremove("xlab"), 
          p_rise+ rremove("ylab") + rremove("xlab"), 
          p_rf+ rremove("ylab") + rremove("xlab"), 
          p_level+ rremove("ylab") + rremove("xlab"),
          nrow = 4, ncol = 1, 
          labels = c('A', 'B', 'C', 'D'), 
          font.label = list(size = 30, family= 'Times New Roman'))

annotate_figure(p_all, 
                left = text_grob("Log-f0 (Z-Scores)", rot = 90, vjust = 1, 
                                 size = 25, family= 'Times New Roman'),
                bottom = text_grob("Normalised time", 
                                   size = 25, family= 'Times New Roman'))

ggsave(filename = file.path(plot_dir, "hl_compare.jpeg"),width = 7, height = 12, dpi = 300)
```


```{r, warning=FALSE, message=FALSE}
# grouped by speaker
p_cluster(f0_di_ct_lcmh_p_fall, sandhi_tone, 'speaker')
p_cluster(f0_di_ct_lcmh_p_rise, sandhi_tone, 'speaker')
p_cluster(f0_di_ct_lcmh_s_rf, sandhi_tone, 'speaker')
p_cluster(f0_di_ct_lcmh_s_rise, sandhi_tone, 'speaker')
```


```{r warning=FALSE}
# distribution by speaker
f0_di_ct_lcmh_hs <- f0_di_ct_lcmh_hs %>% 
  mutate(sandhi_tone = factor(sandhi_tone, levels = c('MHHL','HHHH', 'MMMH')))
f0_di_ct_lcmh_ls <- f0_di_ct_lcmh_ls %>% 
  mutate(sandhi_tone = factor(sandhi_tone, levels = c('LLHL','LLHH')))

p_dist_hs <- distri_prop2(f0_di_ct_lcmh_hs, speaker, sandhi_tone)+
  theme(legend.position = 'top'); p_dist_hs
p_dist_ls <- distri_prop2(f0_di_ct_lcmh_ls, speaker, sandhi_tone)+
  theme(legend.position = 'top'); p_dist_ls

p_dist_s <- ggarrange(p_dist_hs+ rremove("ylab") + rremove("xlab"),
                      p_dist_ls+ rremove("ylab") + rremove("xlab")); p_dist_s

annotate_figure(p_dist_s,
                left = text_grob("frequency proportion", rot = 90, vjust = 1, 
                                 size = 25, family= 'Times New Roman'),
                bottom = text_grob("speaker", 
                                   size = 25, family= 'Times New Roman'))
ggsave(filename = file.path(plot_dir, "hl_dist_speaker.jpeg"),width = 11, height = 5, dpi = 300)
xw```

