---
title: "Analysis of trisyllabic citation tone sandhi patterns in
  Xiangshan"
output: html_document
date: "2024-04-27"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)
library(gridExtra) 
library(ggthemes)
library(viridis)
library(plotly)
library(ggrepel)
library(kml)
```

# Data preparations  
```{r data-construction, cache=FALSE}
load("XSTSF_production.RData")
source('functions.R')

f0_all_ct <- f0_all_pre %>% filter(focus_condition == 'ct' ) %>% 
  group_by(speaker) %>% 
  mutate(norm_f0 = scale(log(f0))) %>% 
  ungroup()

f0_tri_ct <- f0_all_ct %>% filter(diortri == 'tri') 
unique(f0_tri_ct$syntax)

f0_tri_ct_12mh <- f0_tri_ct %>% filter(syntax == '1+2MH')
f0_tri_ct_12vo <- f0_tri_ct %>% filter(syntax == '1+2VO')
f0_tri_ct_21vl <- f0_tri_ct %>% filter(syntax == '2+1VL')
f0_tri_ct_21ll <- f0_tri_ct %>% filter(syntax == '2+1LL')
```

# Initial data inspection

1+2MH
```{r fig.height=8}
unique(f0_tri_ct_12mh$hist_tone1)

# yinping-initial VO
f0_tri_ct_12mh_hp <- f0_tri_ct_12mh %>% filter(hist_tone1 == 'yinping')
ggplotly(draw_by(f0_tri_ct_12mh_hp, 'speaker'), tooltip = c('text', 'x'))

# yinshang-initial VO
f0_tri_ct_12mh_hs <- f0_tri_ct_12mh %>% filter(hist_tone1 == 'yinshang')
ggplotly(draw_by(f0_tri_ct_12mh_hs, 'speaker'), tooltip = c('text', 'x'))

# yangshang-initial VO
f0_tri_ct_12mh_ls <- f0_tri_ct_12mh %>% filter(hist_tone1 == 'yangshang')
ggplotly(draw_by(f0_tri_ct_12mh_ls, 'speaker'), tooltip = c('text', 'x'))
```

1+2VO
```{r fig.height=8}
unique(f0_tri_ct_12vo$hist_tone1)

# yinshang-initial VO
f0_tri_ct_12vo_hs <- f0_tri_ct_12vo %>% filter(hist_tone1 == 'yinshang')
ggplotly(draw_by(f0_tri_ct_12vo_hs, 'speaker'), tooltip = c('text', 'x'))

# yangshang-initial VO
f0_tri_ct_12vo_ls <- f0_tri_ct_12vo %>% filter(hist_tone1 == 'yangshang')
ggplotly(draw_by(f0_tri_ct_12vo_ls, 'speaker'), tooltip = c('text', 'x'))
```

2+1VL
```{r fig.height=8}
unique(f0_tri_ct_21vl$hist_tone1)

# yinping-initial VO
f0_tri_ct_21vl_hp <- f0_tri_ct_21vl %>% filter(hist_tone1 == 'yinping')
ggplotly(draw_by(f0_tri_ct_21vl_hp, 'speaker'), tooltip = c('text', 'x'))


# yangshang-initial VO
f0_tri_ct_21vl_ls <- f0_tri_ct_21vl %>% filter(hist_tone1 == 'yangshang')
ggplotly(draw_by(f0_tri_ct_21vl_ls, 'speaker'), tooltip = c('text', 'x'))

# yangqu-initial VO
f0_tri_ct_21vl_lq <- f0_tri_ct_21vl %>% filter(hist_tone1 == 'yangshang')
ggplotly(draw_by(f0_tri_ct_21vl_lq, 'speaker'), tooltip = c('text', 'x'))
```


2+1LL
```{r fig.height=8}
unique(f0_tri_ct_21ll$hist_tone1)

# yinping-initial VO
f0_tri_ct_21ll_hp <- f0_tri_ct_21ll %>% filter(hist_tone1 == 'yinping')
ggplotly(draw_by(f0_tri_ct_21ll_hp, 'speaker'), tooltip = c('text', 'x'))

# yinshang-initial VO
f0_tri_ct_21ll_hs <- f0_tri_ct_21ll %>% filter(hist_tone1 == 'yinshang')
ggplotly(draw_by(f0_tri_ct_21ll_hs, 'speaker'), tooltip = c('text', 'x'))

# yangping-initial VO
f0_tri_ct_21ll_lp <- f0_tri_ct_21ll %>% filter(hist_tone1 == 'yangping')
ggplotly(draw_by(f0_tri_ct_21ll_lp, 'speaker'), tooltip = c('text', 'x'))
```

