---
title: "[XSTSF] Tone sandhi patterns for trisyllabic tokens"
output: html_document
author: Yibing Shi
date: "Last updated: 2023-07-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(tidyverse)
library(kableExtra) 
library(ggplot2)

library(gridExtra) 
library(ggpubr)
library(plotly)
library(writexl)
library(readxl)
```


## Data construction     
```{r data-construction}
load('XSTSF_production.RData') # load pre-processed data
f0_tri <- f0_all_pre %>% filter(diortri == 'tri')

kable(f0_tri) %>%
  kable_styling("striped", full_width = F) %>%
  scroll_box(width = "100%", height = "300px")
```

<br>

## Data visualisation  
A function to draw plots and save them to lists
```{r function}
draw_by <- function(dataframe, x, y){
            no.list <- as.list(unique(get(x, dataframe)))
            if (missing(y)) {
              p.list <- lapply(no.list, function(i){
                      p <- dataframe %>%
                        filter(eval(as.name(x)) == i) %>%
                        ggplot(aes(x=factor(time), y=norm_f0, group=interaction(syllable_no, ind_no), color=ind_no, linetype=ind_no))+
                        geom_line()+
                        ylim(-2.5, 2.5)+
                        labs(title = paste(x, i, sep = '_'))
                      p
                      })
              p.list
            } else {
              p.list <- lapply(no.list, function(i){
                      p <- dataframe %>%
                        filter(eval(as.name(x)) == i) %>%
                        ggplot(aes(x=factor(time), y=norm_f0, group=interaction(syllable_no, ind_no), color=ind_no, linetype=ind_no))+
                        geom_line()+
                        ylim(-2.5, 2.5)+
                        facet_wrap(as.formula(paste("~", y)))+
                        labs(title = paste(x, i, sep = '_'))
                      p
                      })
              p.list
            }
}
```


### Citation sandhi     
Display the unique tokens under each syntax+starting tone category.
```{r data-ct}
f0_tri_ct <- f0_tri %>% filter(focus_condition == 'citation')
f0_tri_ct_labels <- unique(filter(f0_tri, focus_condition == 'citation')[c('syntax', 'citation_no', 'token')]) %>% arrange(syntax, citation_no)

kable(f0_tri_ct_labels) %>%
  kable_styling("striped", full_width = F) %>%
  scroll_box(width = "100%", height = "300px")
```

Plotting & saving f0 contours for each token, grouped by syntax & starting tone categories
```{r plot-ind-all, out.width='50%', warning=FALSE}
for (var in unique(f0_tri_ct$syntax)) {
  dataframe <- f0_tri_ct %>% filter(syntax == var)
  var2 <- gsub('+', '', var, fixed = TRUE)
  assign(paste0('ct_', var2), draw_by(dataframe, 'citation_no'))
}

# Example: 12MH_RF
for (var in ct_12MH_RF) {
  print(ggplotly(var))
}
```


### Sandhi contours across focus conditions  
```{r data-focus-all}
# select tokens that appear in all the focus conditions
f0_tri_all.con <- f0_tri %>% add_count(token) %>% filter(n == 8*30*6) 
f0_tri_all.con$focus_condition <- factor(f0_tri_all.con$focus_condition, levels = c('citation', 'tri', 'di_3', '1', '2', '3'))
f0_tri_all.con <- f0_tri_all.con %>% arrange(citation_no, focus_condition)

# plotting & saving
for (var in unique(f0_tri_all.con$syntax)) {
  dataframe <- f0_tri_all.con %>% filter(syntax == var)
  var2 <- gsub('+', '', var, fixed = TRUE)
  assign(paste0('all_con_', var2), draw_by(dataframe, 'citation_no', 'focus_condition'))
}

# Example: 21LL_RF
for (var in all_con_21LL_RF) {
  print(ggplotly(var))
}
```



